# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class CitedAnswer(BaseModel):
    answer: typing.Optional[str] = None
    concept_ids: typing.List[str]
    remaining_uncertainties: typing.List[str]

class DerivationResult(BaseModel):
    observations: typing.List["DerivedObservation"]

class DerivedObservation(BaseModel):
    kind: typing.Optional[types.ObservationKind] = None
    text: typing.Optional[str] = None
    locator_kind: typing.Optional[types.LocatorKind] = None
    locator_value: typing.Optional[str] = None
    relationship_subject: typing.Optional[str] = None
    relationship_type: typing.Optional[str] = None
    relationship_object: typing.Optional[str] = None

class ResearchPlan(BaseModel):
    existing_evidence_summary: typing.Optional[str] = None
    missing_evidence: typing.List[str]
    searches: typing.List[str]
    completion_criteria: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################


# #########################################################################
# Model rebuilds (4)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
CitedAnswer.model_rebuild()
DerivationResult.model_rebuild()
DerivedObservation.model_rebuild()
ResearchPlan.model_rebuild()
