# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CitedAnswer": types.CitedAnswer,
    "stream_types.CitedAnswer": stream_types.CitedAnswer,

    "types.DerivationResult": types.DerivationResult,
    "stream_types.DerivationResult": stream_types.DerivationResult,

    "types.DerivedObservation": types.DerivedObservation,
    "stream_types.DerivedObservation": stream_types.DerivedObservation,

    "types.ResearchPlan": types.ResearchPlan,
    "stream_types.ResearchPlan": stream_types.ResearchPlan,


    "types.LocatorKind": types.LocatorKind,

    "types.ObservationKind": types.ObservationKind,

}