# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class LocatorKind(str, Enum):
    Line = "Line"
    Page = "Page"
    Timestamp = "Timestamp"
    Heading = "Heading"

class ObservationKind(str, Enum):
    Entity = "Entity"
    Fact = "Fact"
    Claim = "Claim"
    Procedure = "Procedure"
    Relationship = "Relationship"
    Recommendation = "Recommendation"
    Gap = "Gap"

# #########################################################################
# Generated classes (4)
# #########################################################################

class CitedAnswer(BaseModel):
    answer: str
    concept_ids: typing.List[str]
    remaining_uncertainties: typing.List[str]

class DerivationResult(BaseModel):
    observations: typing.List["DerivedObservation"]

class DerivedObservation(BaseModel):
    kind: ObservationKind
    text: str
    locator_kind: LocatorKind
    locator_value: str
    relationship_subject: typing.Optional[str] = None
    relationship_type: typing.Optional[str] = None
    relationship_object: typing.Optional[str] = None

class ResearchPlan(BaseModel):
    existing_evidence_summary: str
    missing_evidence: typing.List[str]
    searches: typing.List[str]
    completion_criteria: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################


# #########################################################################
# Model rebuilds (4)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
CitedAnswer.model_rebuild()
DerivationResult.model_rebuild()
DerivedObservation.model_rebuild()
ResearchPlan.model_rebuild()
