/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum LocatorKind {
  Line = "Line",
  Page = "Page",
  Timestamp = "Timestamp",
  Heading = "Heading",
}

export enum ObservationKind {
  Entity = "Entity",
  Fact = "Fact",
  Claim = "Claim",
  Procedure = "Procedure",
  Relationship = "Relationship",
  Recommendation = "Recommendation",
  Gap = "Gap",
}

export interface CitedAnswer {
  answer: string
  concept_ids: string[]
  remaining_uncertainties: string[]
  
}

export interface DerivationResult {
  observations: DerivedObservation[]
  
}

export interface DerivedObservation {
  kind: ObservationKind
  text: string
  locator_kind: LocatorKind
  locator_value: string
  relationship_subject?: string | null
  relationship_type?: string | null
  relationship_object?: string | null
  
}

export interface ResearchPlan {
  existing_evidence_summary: string
  missing_evidence: string[]
  searches: string[]
  completion_criteria: string[]
  
}
